#!/bin/bash

cd $OPENSHIFT_REPO_DIR

PGPASSWORD=$OPENSHIFT_POSTGRESQL_DB_PASSWORD psql -h $OPENSHIFT_POSTGRESQL_DB_HOST -U $OPENSHIFT_POSTGRESQL_DB_USERNAME $PGDATABASE -c "create extension if not exists unaccent"

echo "Executing 'python manage.py migrate'"
python manage.py migrate