#!/bin/bash

#simple script to start both servers 

DIR=/home/ivan/workspace/mapy
USER=ivan
PYTHON=bin/python

do_start () {
cd $DIR
sudo -b -H -u $USER $PYTHON runsocketio.py 1>/dev/null 2>&1
sudo -b -H -u $USER $PYTHON manage.py process_server 1>/dev/null 2>&1

}

do_stop () {
pkill -f runsocketio.py
pkill -f process_server
}

do_status () {

ps -ef|grep runsocketio.py|grep -vP "grep|sudo"
ps -ef|grep process_server|grep -vP "grep|sudo"
}

case "$1" in
	start)
	 do_start
	 ;;
  stop)
  	do_stop
  	;;
  status)
  	do_status
  	;;
  *)
	echo "Usage: mp-servers start|stop|status" >&2
	exit 3
  	
esac